/*
  Password hashing migration.
  Run once on an existing course/development database after
  004_add_review_integrity.sql.

  The known seed accounts are replaced with hashes generated by ASP.NET Core
  PasswordHasher<User>. The script deliberately does not keep a plaintext
  login fallback. If additional legacy plaintext accounts exist, it stops
  before changing data so those accounts can be reset explicitly.
*/

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;
SET DEFINE OFF;

DECLARE
    unsupported_legacy_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO unsupported_legacy_count
    FROM users
    WHERE username NOT IN ('admin', 'user001', 'runner001')
      AND NOT REGEXP_LIKE(password_hash, '^AQ[A-Za-z0-9+/]{80}==$');

    IF unsupported_legacy_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20051,
            'Password migration stopped: non-seed legacy passwords require an explicit reset.'
        );
    END IF;
END;
/

ALTER TABLE users MODIFY (password_hash VARCHAR2(256 CHAR));

UPDATE users
SET password_hash = 'AQAAAAIAAYagAAAAEPqJQAv/Vo1Jz5tjcxAJory+Zwgb3v6BzbtfK3FaBgjx/U8bo68KilsseZi3DlW45Q=='
WHERE username = 'admin'
  AND NOT REGEXP_LIKE(password_hash, '^AQ[A-Za-z0-9+/]{80}==$');

UPDATE users
SET password_hash = 'AQAAAAIAAYagAAAAEOx/t+yETiCAwdivPYWUOsvmBUUx03cVjrwfuc7y2NmYl2Rb+jREtOsOSKV753GP+w=='
WHERE username = 'user001'
  AND NOT REGEXP_LIKE(password_hash, '^AQ[A-Za-z0-9+/]{80}==$');

UPDATE users
SET password_hash = 'AQAAAAIAAYagAAAAEIHg+08BaIBhSacEvUe36qaRgTvu/0GFfvPvpBFq6QgpFZGwh56OdPa4COqdMrndsQ=='
WHERE username = 'runner001'
  AND NOT REGEXP_LIKE(password_hash, '^AQ[A-Za-z0-9+/]{80}==$');

DECLARE
    invalid_hash_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO invalid_hash_count
    FROM users
    WHERE NOT REGEXP_LIKE(password_hash, '^AQ[A-Za-z0-9+/]{80}==$');

    IF invalid_hash_count > 0 THEN
        RAISE_APPLICATION_ERROR(
            -20052,
            'Password migration failed: one or more users still have an invalid password hash.'
        );
    END IF;
END;
/

COMMENT ON COLUMN users.password_hash IS
    'ASP.NET Core PasswordHasher<User> 生成的带盐密码哈希，禁止保存原始密码';

COMMIT;

PROMPT Password hash migration completed successfully.
