/*
  校园中转分发与跑腿服务管理系统 Oracle 建库脚本
  依据《校园中转分发与跑腿服务管理系统-数据库设计文档.docx》中的 24 张关系表生成。
  适用：Oracle 18c 或更高版本。

  使用方法：
  1. 使用具有建表权限的 Oracle 用户登录 SQL Developer / SQL*Plus。
  2. 直接执行本文件。
  3. 若是第一次执行，前面的 DROP TABLE 会自动忽略“表不存在”的错误。
*/

SET DEFINE OFF;

/* =========================
   1. 删除旧表：按外键依赖反向删除
   ========================= */
BEGIN EXECUTE IMMEDIATE 'DROP TABLE report_audit_items CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reports CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE audit_refund_checks CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE audit_payment_checks CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE audit_status_log_checks CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE audit_logs CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE settlement_payment_items CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE settlements CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE complaints CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE reviews CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE refunds CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE payments CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE task_status_logs CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE assign_records CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE private_task_details CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE express_pickup_details CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE food_delivery_details CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE tasks CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE service_node_rules CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE service_types CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE nodes CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE runners CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE user_addresses CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE users CASCADE CONSTRAINTS PURGE'; EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; END;
/

/* =========================
   2. 基础账户、地址、跑腿员表
   ========================= */
CREATE TABLE users (
    user_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username        VARCHAR2(50 CHAR)  NOT NULL,
    phone           VARCHAR2(20 CHAR)  NOT NULL,
    password_hash   VARCHAR2(128 CHAR) NOT NULL,
    user_role       VARCHAR2(20 CHAR)  DEFAULT 'USER' NOT NULL,
    account_status  VARCHAR2(20 CHAR)  DEFAULT 'NORMAL' NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (user_id),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_phone UNIQUE (phone),
    CONSTRAINT ck_users_role CHECK (user_role IN ('USER', 'RUNNER', 'ADMIN')),
    CONSTRAINT ck_users_status CHECK (account_status IN ('NORMAL', 'DISABLED'))
);

COMMENT ON TABLE users IS '系统用户账号、角色和账号状态';
COMMENT ON COLUMN users.user_id IS '用户编号，主键，身份列';
COMMENT ON COLUMN users.username IS '账号，唯一，非空';
COMMENT ON COLUMN users.phone IS '手机号，唯一，非空';
COMMENT ON COLUMN users.password_hash IS '密码散列值，非空';
COMMENT ON COLUMN users.user_role IS '用户角色：USER/RUNNER/ADMIN';
COMMENT ON COLUMN users.account_status IS '账号状态：NORMAL/DISABLED';

CREATE TABLE user_addresses (
    user_id         NUMBER NOT NULL,
    address_no      NUMBER NOT NULL,
    contact_name    VARCHAR2(50 CHAR)  NOT NULL,
    contact_phone   VARCHAR2(20 CHAR)  NOT NULL,
    campus          VARCHAR2(50 CHAR)  NOT NULL,
    building_room   VARCHAR2(120 CHAR) NOT NULL,
    is_default      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    CONSTRAINT pk_user_addresses PRIMARY KEY (user_id, address_no),
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT ck_user_addresses_default CHECK (is_default IN ('Y', 'N'))
);

COMMENT ON TABLE user_addresses IS '用户常用地址弱实体表';
COMMENT ON COLUMN user_addresses.user_id IS '所属用户编号，联合主键，外键';
COMMENT ON COLUMN user_addresses.address_no IS '地址序号，联合主键，弱实体部分键';
COMMENT ON COLUMN user_addresses.contact_name IS '联系人';
COMMENT ON COLUMN user_addresses.contact_phone IS '联系电话';
COMMENT ON COLUMN user_addresses.campus IS '校区';
COMMENT ON COLUMN user_addresses.building_room IS '楼栋房间';
COMMENT ON COLUMN user_addresses.is_default IS '默认地址标志：Y/N';

CREATE TABLE runners (
    runner_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id        NUMBER NOT NULL,
    real_name      VARCHAR2(50 CHAR)  NOT NULL,
    identity_info  VARCHAR2(200 CHAR) NOT NULL,
    audit_status   VARCHAR2(20 CHAR)  DEFAULT 'PENDING' NOT NULL,
    work_status    VARCHAR2(20 CHAR)  DEFAULT 'OFFLINE' NOT NULL,
    credit_score   NUMBER DEFAULT 100 NOT NULL,
    CONSTRAINT pk_runners PRIMARY KEY (runner_id),
    CONSTRAINT uk_runners_user UNIQUE (user_id),
    CONSTRAINT fk_runners_user FOREIGN KEY (user_id)
        REFERENCES users(user_id),
    CONSTRAINT ck_runners_audit CHECK (audit_status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_runners_work CHECK (work_status IN ('FREE', 'BUSY', 'OFFLINE')),
    CONSTRAINT ck_runners_credit CHECK (credit_score >= 0)
);

COMMENT ON TABLE runners IS '用户申请成为跑腿员后的资格资料和接单状态';
COMMENT ON COLUMN runners.runner_id IS '跑腿员编号，主键，身份列';
COMMENT ON COLUMN runners.user_id IS '关联用户，一对一，唯一外键';
COMMENT ON COLUMN runners.real_name IS '真实姓名';
COMMENT ON COLUMN runners.identity_info IS '身份信息';
COMMENT ON COLUMN runners.audit_status IS '审核状态：PENDING/APPROVED/REJECTED';
COMMENT ON COLUMN runners.work_status IS '接单状态：FREE/BUSY/OFFLINE';
COMMENT ON COLUMN runners.credit_score IS '信誉分，默认100';

/* =========================
   3. 节点、服务类型与适用规则表
   ========================= */
CREATE TABLE nodes (
    node_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    node_type    VARCHAR2(30 CHAR) NOT NULL,
    node_name    VARCHAR2(80 CHAR) NOT NULL,
    location     VARCHAR2(200 CHAR) NOT NULL,
    open_time    VARCHAR2(100 CHAR),
    node_status  VARCHAR2(20 CHAR) DEFAULT 'NORMAL' NOT NULL,
    CONSTRAINT pk_nodes PRIMARY KEY (node_id),
    CONSTRAINT ck_nodes_status CHECK (node_status IN ('NORMAL', 'CLOSED'))
);

COMMENT ON TABLE nodes IS '校内交接节点、驿站或分发点信息';
COMMENT ON COLUMN nodes.node_id IS '节点编号，主键，身份列';
COMMENT ON COLUMN nodes.node_type IS '节点类型，如 GATE/STATION/DISTRIBUTION';
COMMENT ON COLUMN nodes.node_name IS '节点名称';
COMMENT ON COLUMN nodes.location IS '具体位置';
COMMENT ON COLUMN nodes.open_time IS '开放时间';
COMMENT ON COLUMN nodes.node_status IS '节点状态：NORMAL/CLOSED';

CREATE TABLE service_types (
    service_type_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    service_name     VARCHAR2(50 CHAR) NOT NULL,
    base_price       NUMBER(10,2) NOT NULL,
    distance_rule    VARCHAR2(200 CHAR),
    urgent_rule      VARCHAR2(200 CHAR),
    type_status      VARCHAR2(20 CHAR) DEFAULT 'ENABLED' NOT NULL,
    CONSTRAINT pk_service_types PRIMARY KEY (service_type_id),
    CONSTRAINT ck_service_price CHECK (base_price >= 0),
    CONSTRAINT ck_service_status CHECK (type_status IN ('ENABLED', 'DISABLED'))
);

COMMENT ON TABLE service_types IS '服务类型及价格规则';
COMMENT ON COLUMN service_types.service_type_id IS '服务类型编号，主键，身份列';
COMMENT ON COLUMN service_types.service_name IS '服务名称';
COMMENT ON COLUMN service_types.base_price IS '基础价格';
COMMENT ON COLUMN service_types.distance_rule IS '距离规则';
COMMENT ON COLUMN service_types.urgent_rule IS '加急规则';
COMMENT ON COLUMN service_types.type_status IS '类型状态：ENABLED/DISABLED';

CREATE TABLE service_node_rules (
    service_type_id  NUMBER NOT NULL,
    node_id          NUMBER NOT NULL,
    CONSTRAINT pk_service_node_rules PRIMARY KEY (service_type_id, node_id),
    CONSTRAINT fk_snr_service FOREIGN KEY (service_type_id)
        REFERENCES service_types(service_type_id) ON DELETE CASCADE,
    CONSTRAINT fk_snr_node FOREIGN KEY (node_id)
        REFERENCES nodes(node_id) ON DELETE CASCADE
);

COMMENT ON TABLE service_node_rules IS '服务类型与节点之间的适用节点多对多联系';
COMMENT ON COLUMN service_node_rules.service_type_id IS '服务类型编号，联合主键，外键';
COMMENT ON COLUMN service_node_rules.node_id IS '节点编号，联合主键，外键';

/* =========================
   4. 任务主单与三类任务明细表
   ========================= */
CREATE TABLE tasks (
    task_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    publisher_user_id  NUMBER NOT NULL,
    service_type_id    NUMBER NOT NULL,
    address_no         NUMBER NOT NULL,
    node_id            NUMBER NOT NULL,
    task_title         VARCHAR2(100 CHAR) NOT NULL,
    task_price         NUMBER(10,2) NOT NULL,
    urgent_flag        CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    task_status        VARCHAR2(30 CHAR) DEFAULT 'CREATED' NOT NULL,
    created_at         DATE DEFAULT SYSDATE NOT NULL,
    completed_at       DATE,
    CONSTRAINT pk_tasks PRIMARY KEY (task_id),
    CONSTRAINT fk_tasks_user FOREIGN KEY (publisher_user_id)
        REFERENCES users(user_id),
    CONSTRAINT fk_tasks_service FOREIGN KEY (service_type_id)
        REFERENCES service_types(service_type_id),
    CONSTRAINT fk_tasks_address FOREIGN KEY (publisher_user_id, address_no)
        REFERENCES user_addresses(user_id, address_no),
    CONSTRAINT fk_tasks_node FOREIGN KEY (node_id)
        REFERENCES nodes(node_id),
    CONSTRAINT fk_tasks_service_node FOREIGN KEY (service_type_id, node_id)
        REFERENCES service_node_rules(service_type_id, node_id),
    CONSTRAINT ck_tasks_price CHECK (task_price >= 0),
    CONSTRAINT ck_tasks_urgent CHECK (urgent_flag IN ('Y', 'N')),
    CONSTRAINT ck_tasks_status CHECK (task_status IN (
        'CREATED', 'PAID', 'WAITING', 'ASSIGNED', 'PICKED_UP',
        'DELIVERING', 'WAIT_CONFIRM', 'FINISHED', 'CANCELLED', 'REFUNDING'
    )),
    CONSTRAINT ck_tasks_time CHECK (completed_at IS NULL OR completed_at >= created_at)
);

COMMENT ON TABLE tasks IS '任务主单公共字段，关联发布用户、服务类型、地址和交接节点';
COMMENT ON COLUMN tasks.task_id IS '任务编号，主键，身份列';
COMMENT ON COLUMN tasks.publisher_user_id IS '发布用户编号';
COMMENT ON COLUMN tasks.service_type_id IS '服务类型编号';
COMMENT ON COLUMN tasks.address_no IS '使用地址序号，与 publisher_user_id 共同引用 user_addresses';
COMMENT ON COLUMN tasks.node_id IS '交接节点编号，同时与 service_type_id 共同引用 service_node_rules';
COMMENT ON COLUMN tasks.task_title IS '任务标题';
COMMENT ON COLUMN tasks.task_price IS '任务价格';
COMMENT ON COLUMN tasks.urgent_flag IS '加急标志：Y/N';
COMMENT ON COLUMN tasks.task_status IS '任务状态';
COMMENT ON COLUMN tasks.created_at IS '创建时间，默认 SYSDATE';
COMMENT ON COLUMN tasks.completed_at IS '完成时间';

CREATE TABLE food_delivery_details (
    task_id             NUMBER NOT NULL,
    detail_no           NUMBER NOT NULL,
    merchant_name       VARCHAR2(100 CHAR) NOT NULL,
    platform_order_no   VARCHAR2(80 CHAR),
    pickup_note         VARCHAR2(200 CHAR),
    CONSTRAINT pk_food_delivery_details PRIMARY KEY (task_id, detail_no),
    CONSTRAINT fk_food_task FOREIGN KEY (task_id)
        REFERENCES tasks(task_id) ON DELETE CASCADE
);

COMMENT ON TABLE food_delivery_details IS '外卖分发任务专有明细弱实体表';
COMMENT ON COLUMN food_delivery_details.task_id IS '任务编号，联合主键，外键';
COMMENT ON COLUMN food_delivery_details.detail_no IS '明细序号，联合主键，弱实体部分键';
COMMENT ON COLUMN food_delivery_details.merchant_name IS '商家名称';
COMMENT ON COLUMN food_delivery_details.platform_order_no IS '平台订单号';
COMMENT ON COLUMN food_delivery_details.pickup_note IS '取餐备注';

CREATE TABLE express_pickup_details (
    task_id          NUMBER NOT NULL,
    detail_no        NUMBER NOT NULL,
    express_company  VARCHAR2(80 CHAR) NOT NULL,
    waybill_no       VARCHAR2(80 CHAR) NOT NULL,
    pickup_code      VARCHAR2(50 CHAR) NOT NULL,
    pickup_note      VARCHAR2(200 CHAR),
    CONSTRAINT pk_express_pickup_details PRIMARY KEY (task_id, detail_no),
    CONSTRAINT fk_express_task FOREIGN KEY (task_id)
        REFERENCES tasks(task_id) ON DELETE CASCADE
);

COMMENT ON TABLE express_pickup_details IS '快递代取任务专有明细弱实体表';
COMMENT ON COLUMN express_pickup_details.task_id IS '任务编号，联合主键，外键';
COMMENT ON COLUMN express_pickup_details.detail_no IS '明细序号，联合主键，弱实体部分键';
COMMENT ON COLUMN express_pickup_details.express_company IS '快递公司';
COMMENT ON COLUMN express_pickup_details.waybill_no IS '物流单号';
COMMENT ON COLUMN express_pickup_details.pickup_code IS '取件码，敏感信息';
COMMENT ON COLUMN express_pickup_details.pickup_note IS '取件备注';

CREATE TABLE private_task_details (
    task_id              NUMBER NOT NULL,
    detail_no            NUMBER NOT NULL,
    item_category        VARCHAR2(50 CHAR) NOT NULL,
    pickup_location      VARCHAR2(200 CHAR) NOT NULL,
    delivery_location    VARCHAR2(200 CHAR) NOT NULL,
    expected_finish_at   DATE,
    description          VARCHAR2(500 CHAR),
    CONSTRAINT pk_private_task_details PRIMARY KEY (task_id, detail_no),
    CONSTRAINT fk_private_task FOREIGN KEY (task_id)
        REFERENCES tasks(task_id) ON DELETE CASCADE
);

COMMENT ON TABLE private_task_details IS '私人物品或私人跑腿任务专有明细弱实体表';
COMMENT ON COLUMN private_task_details.task_id IS '任务编号，联合主键，外键';
COMMENT ON COLUMN private_task_details.detail_no IS '明细序号，联合主键，弱实体部分键';
COMMENT ON COLUMN private_task_details.item_category IS '物品类别';
COMMENT ON COLUMN private_task_details.pickup_location IS '取货地点';
COMMENT ON COLUMN private_task_details.delivery_location IS '送达地点';
COMMENT ON COLUMN private_task_details.expected_finish_at IS '期望完成时间';
COMMENT ON COLUMN private_task_details.description IS '任务描述';

/* =========================
   5. 接派记录与状态流转日志表
   ========================= */
CREATE TABLE assign_records (
    record_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    task_id          NUMBER NOT NULL,
    runner_id        NUMBER NOT NULL,
    operation_type   VARCHAR2(20 CHAR) NOT NULL,
    assigned_at      DATE DEFAULT SYSDATE NOT NULL,
    reassign_reason  VARCHAR2(200 CHAR),
    CONSTRAINT pk_assign_records PRIMARY KEY (record_id),
    CONSTRAINT fk_assign_task FOREIGN KEY (task_id)
        REFERENCES tasks(task_id),
    CONSTRAINT fk_assign_runner FOREIGN KEY (runner_id)
        REFERENCES runners(runner_id),
    CONSTRAINT ck_assign_operation CHECK (operation_type IN ('SELF', 'ADMIN', 'REASSIGN'))
);

COMMENT ON TABLE assign_records IS '任务接单、派单和重派记录';
COMMENT ON COLUMN assign_records.record_id IS '记录编号，主键，身份列';
COMMENT ON COLUMN assign_records.task_id IS '任务编号，外键';
COMMENT ON COLUMN assign_records.runner_id IS '跑腿员编号，外键';
COMMENT ON COLUMN assign_records.operation_type IS '操作类型：SELF/ADMIN/REASSIGN';
COMMENT ON COLUMN assign_records.assigned_at IS '接派时间，默认 SYSDATE';
COMMENT ON COLUMN assign_records.reassign_reason IS '重派原因';

CREATE TABLE task_status_logs (
    log_id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id         NUMBER NOT NULL,
    status_before     VARCHAR2(30 CHAR),
    status_after      VARCHAR2(30 CHAR) NOT NULL,
    operator_user_id  NUMBER NOT NULL,
    operated_at       DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT pk_task_status_logs PRIMARY KEY (log_id),
    CONSTRAINT fk_status_record FOREIGN KEY (record_id)
        REFERENCES assign_records(record_id) ON DELETE CASCADE,
    CONSTRAINT fk_status_operator FOREIGN KEY (operator_user_id)
        REFERENCES users(user_id)
);

COMMENT ON TABLE task_status_logs IS '接派记录对应的任务状态流转日志';
COMMENT ON COLUMN task_status_logs.log_id IS '日志编号，主键，身份列';
COMMENT ON COLUMN task_status_logs.record_id IS '接派记录编号，外键';
COMMENT ON COLUMN task_status_logs.status_before IS '变化前状态，可空';
COMMENT ON COLUMN task_status_logs.status_after IS '变化后状态，非空';
COMMENT ON COLUMN task_status_logs.operator_user_id IS '操作人用户编号，外键';
COMMENT ON COLUMN task_status_logs.operated_at IS '操作时间，默认 SYSDATE';

/* =========================
   6. 支付、退款、评价、投诉、结算表
   ========================= */
CREATE TABLE payments (
    payment_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id       NUMBER NOT NULL,
    order_amount    NUMBER(10,2) NOT NULL,
    pay_amount      NUMBER(10,2) NOT NULL,
    pay_method      VARCHAR2(30 CHAR) NOT NULL,
    third_trade_no  VARCHAR2(100 CHAR),
    pay_status      VARCHAR2(20 CHAR) DEFAULT 'UNPAID' NOT NULL,
    CONSTRAINT pk_payments PRIMARY KEY (payment_id),
    CONSTRAINT fk_payments_record FOREIGN KEY (record_id)
        REFERENCES assign_records(record_id),
    CONSTRAINT uk_payments_trade_no UNIQUE (third_trade_no),
    CONSTRAINT ck_payments_order_amount CHECK (order_amount >= 0),
    CONSTRAINT ck_payments_pay_amount CHECK (pay_amount >= 0),
    CONSTRAINT ck_payments_method CHECK (pay_method IN ('WECHAT', 'ALIPAY', 'CASH')),
    CONSTRAINT ck_payments_status CHECK (pay_status IN ('UNPAID', 'PAID', 'FAILED', 'REFUNDED'))
);

COMMENT ON TABLE payments IS '围绕接派记录产生的支付记录';
COMMENT ON COLUMN payments.payment_id IS '支付编号，主键，身份列';
COMMENT ON COLUMN payments.record_id IS '接派记录编号，外键';
COMMENT ON COLUMN payments.order_amount IS '订单金额';
COMMENT ON COLUMN payments.pay_amount IS '实际支付金额';
COMMENT ON COLUMN payments.pay_method IS '支付方式：WECHAT/ALIPAY/CASH';
COMMENT ON COLUMN payments.third_trade_no IS '第三方交易流水号，唯一，可空';
COMMENT ON COLUMN payments.pay_status IS '支付状态：UNPAID/PAID/FAILED/REFUNDED';

CREATE TABLE refunds (
    refund_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    payment_id       NUMBER NOT NULL,
    refund_amount    NUMBER(10,2) NOT NULL,
    refund_reason    VARCHAR2(300 CHAR) NOT NULL,
    approved_amount  NUMBER(10,2),
    process_status   VARCHAR2(20 CHAR) DEFAULT 'APPLY' NOT NULL,
    CONSTRAINT pk_refunds PRIMARY KEY (refund_id),
    CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id),
    CONSTRAINT ck_refunds_amount CHECK (refund_amount >= 0),
    CONSTRAINT ck_refunds_approved CHECK (approved_amount IS NULL OR approved_amount >= 0),
    CONSTRAINT ck_refunds_status CHECK (process_status IN ('APPLY', 'APPROVED', 'REJECTED', 'DONE'))
);

COMMENT ON TABLE refunds IS '支付记录衍生的退款申请和处理信息';
COMMENT ON COLUMN refunds.refund_id IS '退款编号，主键，身份列';
COMMENT ON COLUMN refunds.payment_id IS '支付编号，外键';
COMMENT ON COLUMN refunds.refund_amount IS '申请退款金额';
COMMENT ON COLUMN refunds.refund_reason IS '申请原因';
COMMENT ON COLUMN refunds.approved_amount IS '核定金额';
COMMENT ON COLUMN refunds.process_status IS '处理状态：APPLY/APPROVED/REJECTED/DONE';

CREATE TABLE reviews (
    review_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id       NUMBER NOT NULL,
    rating          NUMBER NOT NULL,
    anonymous_flag  CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
    comment_text    VARCHAR2(300 CHAR),
    reviewed_at     DATE DEFAULT SYSDATE NOT NULL,
    credit_delta    NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT pk_reviews PRIMARY KEY (review_id),
    CONSTRAINT uk_reviews_record UNIQUE (record_id),
    CONSTRAINT fk_reviews_record FOREIGN KEY (record_id)
        REFERENCES assign_records(record_id),
    CONSTRAINT ck_reviews_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_anonymous CHECK (anonymous_flag IN ('Y', 'N'))
);

COMMENT ON TABLE reviews IS '服务评价及信誉变动结果';
COMMENT ON COLUMN reviews.review_id IS '评价编号，主键，身份列';
COMMENT ON COLUMN reviews.record_id IS '接派记录编号，唯一外键';
COMMENT ON COLUMN reviews.rating IS '星级评分：1-5';
COMMENT ON COLUMN reviews.anonymous_flag IS '匿名标识：Y/N';
COMMENT ON COLUMN reviews.comment_text IS '文字反馈';
COMMENT ON COLUMN reviews.reviewed_at IS '评价时间，默认 SYSDATE';
COMMENT ON COLUMN reviews.credit_delta IS '信誉变动值';

CREATE TABLE complaints (
    complaint_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_id       NUMBER NOT NULL,
    reason          VARCHAR2(300 CHAR) NOT NULL,
    process_status  VARCHAR2(20 CHAR) DEFAULT 'SUBMITTED' NOT NULL,
    process_result  VARCHAR2(500 CHAR),
    CONSTRAINT pk_complaints PRIMARY KEY (complaint_id),
    CONSTRAINT fk_complaints_record FOREIGN KEY (record_id)
        REFERENCES assign_records(record_id),
    CONSTRAINT ck_complaints_status CHECK (process_status IN ('SUBMITTED', 'PROCESSING', 'DONE'))
);

COMMENT ON TABLE complaints IS '针对一次接派服务的投诉及处理结果';
COMMENT ON COLUMN complaints.complaint_id IS '投诉编号，主键，身份列';
COMMENT ON COLUMN complaints.record_id IS '接派记录编号，外键';
COMMENT ON COLUMN complaints.reason IS '投诉原因';
COMMENT ON COLUMN complaints.process_status IS '处理状态：SUBMITTED/PROCESSING/DONE';
COMMENT ON COLUMN complaints.process_result IS '处理结果';

CREATE TABLE settlements (
    settlement_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    runner_id          NUMBER NOT NULL,
    order_total        NUMBER(10,2) NOT NULL,
    platform_fee       NUMBER(10,2) NOT NULL,
    net_income         NUMBER(10,2) NOT NULL,
    settlement_status  VARCHAR2(20 CHAR) DEFAULT 'WAITING' NOT NULL,
    CONSTRAINT pk_settlements PRIMARY KEY (settlement_id),
    CONSTRAINT fk_settlements_runner FOREIGN KEY (runner_id)
        REFERENCES runners(runner_id),
    CONSTRAINT ck_settlements_money CHECK (order_total >= 0 AND platform_fee >= 0 AND net_income >= 0),
    CONSTRAINT ck_settlements_status CHECK (settlement_status IN ('WAITING', 'DONE', 'BLOCKED'))
);

COMMENT ON TABLE settlements IS '跑腿员收入结算主表';
COMMENT ON COLUMN settlements.settlement_id IS '结算编号，主键，身份列';
COMMENT ON COLUMN settlements.runner_id IS '跑腿员编号，外键';
COMMENT ON COLUMN settlements.order_total IS '订单总额';
COMMENT ON COLUMN settlements.platform_fee IS '平台抽成';
COMMENT ON COLUMN settlements.net_income IS '应得净收入';
COMMENT ON COLUMN settlements.settlement_status IS '结算状态：WAITING/DONE/BLOCKED';

CREATE TABLE settlement_payment_items (
    settlement_id  NUMBER NOT NULL,
    payment_id     NUMBER NOT NULL,
    CONSTRAINT pk_settlement_payment_items PRIMARY KEY (settlement_id, payment_id),
    CONSTRAINT uk_spi_payment UNIQUE (payment_id),
    CONSTRAINT fk_spi_settlement FOREIGN KEY (settlement_id)
        REFERENCES settlements(settlement_id) ON DELETE CASCADE,
    CONSTRAINT fk_spi_payment FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
);

COMMENT ON TABLE settlement_payment_items IS '结算单与支付记录之间的结算依据联系';
COMMENT ON COLUMN settlement_payment_items.settlement_id IS '结算编号，联合主键，外键';
COMMENT ON COLUMN settlement_payment_items.payment_id IS '支付编号，联合主键，外键，唯一避免重复结算';

/* =========================
   7. 审计与报表表
   ========================= */
CREATE TABLE audit_logs (
    audit_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    audit_object    VARCHAR2(50 CHAR) NOT NULL,
    audit_result    VARCHAR2(20 CHAR) NOT NULL,
    audited_at      DATE DEFAULT SYSDATE NOT NULL,
    exception_note  VARCHAR2(300 CHAR),
    CONSTRAINT pk_audit_logs PRIMARY KEY (audit_id),
    CONSTRAINT ck_audit_object CHECK (audit_object IN ('LOG', 'PAYMENT', 'REFUND')),
    CONSTRAINT ck_audit_result CHECK (audit_result IN ('PASS', 'ABNORMAL'))
);

COMMENT ON TABLE audit_logs IS '运营审计日志基本信息';
COMMENT ON COLUMN audit_logs.audit_id IS '审计编号，主键，身份列';
COMMENT ON COLUMN audit_logs.audit_object IS '审计对象：LOG/PAYMENT/REFUND';
COMMENT ON COLUMN audit_logs.audit_result IS '审计结果：PASS/ABNORMAL';
COMMENT ON COLUMN audit_logs.audited_at IS '审计时间，默认 SYSDATE';
COMMENT ON COLUMN audit_logs.exception_note IS '异常说明';

CREATE TABLE audit_status_log_checks (
    audit_id  NUMBER NOT NULL,
    log_id    NUMBER NOT NULL,
    CONSTRAINT pk_audit_status_log_checks PRIMARY KEY (audit_id, log_id),
    CONSTRAINT fk_aslc_audit FOREIGN KEY (audit_id)
        REFERENCES audit_logs(audit_id) ON DELETE CASCADE,
    CONSTRAINT fk_aslc_log FOREIGN KEY (log_id)
        REFERENCES task_status_logs(log_id)
);

COMMENT ON TABLE audit_status_log_checks IS '审计日志与任务状态日志之间的抽查联系';
COMMENT ON COLUMN audit_status_log_checks.audit_id IS '审计编号，联合主键，外键';
COMMENT ON COLUMN audit_status_log_checks.log_id IS '状态日志编号，联合主键，外键';

CREATE TABLE audit_payment_checks (
    audit_id    NUMBER NOT NULL,
    payment_id  NUMBER NOT NULL,
    CONSTRAINT pk_audit_payment_checks PRIMARY KEY (audit_id, payment_id),
    CONSTRAINT fk_apc_audit FOREIGN KEY (audit_id)
        REFERENCES audit_logs(audit_id) ON DELETE CASCADE,
    CONSTRAINT fk_apc_payment FOREIGN KEY (payment_id)
        REFERENCES payments(payment_id)
);

COMMENT ON TABLE audit_payment_checks IS '审计日志与支付记录之间的核验联系';
COMMENT ON COLUMN audit_payment_checks.audit_id IS '审计编号，联合主键，外键';
COMMENT ON COLUMN audit_payment_checks.payment_id IS '支付编号，联合主键，外键';

CREATE TABLE audit_refund_checks (
    audit_id   NUMBER NOT NULL,
    refund_id  NUMBER NOT NULL,
    CONSTRAINT pk_audit_refund_checks PRIMARY KEY (audit_id, refund_id),
    CONSTRAINT fk_arc_audit FOREIGN KEY (audit_id)
        REFERENCES audit_logs(audit_id) ON DELETE CASCADE,
    CONSTRAINT fk_arc_refund FOREIGN KEY (refund_id)
        REFERENCES refunds(refund_id)
);

COMMENT ON TABLE audit_refund_checks IS '审计日志与退款记录之间的核验联系';
COMMENT ON COLUMN audit_refund_checks.audit_id IS '审计编号，联合主键，外键';
COMMENT ON COLUMN audit_refund_checks.refund_id IS '退款编号，联合主键，外键';

CREATE TABLE reports (
    report_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    report_type    VARCHAR2(50 CHAR) NOT NULL,
    stat_period    VARCHAR2(50 CHAR) NOT NULL,
    generated_at   DATE DEFAULT SYSDATE NOT NULL,
    report_status  VARCHAR2(20 CHAR) DEFAULT 'GENERATED' NOT NULL,
    CONSTRAINT pk_reports PRIMARY KEY (report_id),
    CONSTRAINT ck_reports_type CHECK (report_type IN ('ORDER', 'PAYMENT', 'COMPLAINT')),
    CONSTRAINT ck_reports_status CHECK (report_status IN ('GENERATED', 'EXPORTED'))
);

COMMENT ON TABLE reports IS '统计报表的类型、周期和生成状态';
COMMENT ON COLUMN reports.report_id IS '报表编号，主键，身份列';
COMMENT ON COLUMN reports.report_type IS '报表类型：ORDER/PAYMENT/COMPLAINT';
COMMENT ON COLUMN reports.stat_period IS '统计周期，如 2026-05 或 2026年第2周';
COMMENT ON COLUMN reports.generated_at IS '生成时间，默认 SYSDATE';
COMMENT ON COLUMN reports.report_status IS '报表状态：GENERATED/EXPORTED';

CREATE TABLE report_audit_items (
    report_id  NUMBER NOT NULL,
    audit_id   NUMBER NOT NULL,
    CONSTRAINT pk_report_audit_items PRIMARY KEY (report_id, audit_id),
    CONSTRAINT fk_rai_report FOREIGN KEY (report_id)
        REFERENCES reports(report_id) ON DELETE CASCADE,
    CONSTRAINT fk_rai_audit FOREIGN KEY (audit_id)
        REFERENCES audit_logs(audit_id)
);

COMMENT ON TABLE report_audit_items IS '统计报表与审计日志之间的生成依据联系';
COMMENT ON COLUMN report_audit_items.report_id IS '报表编号，联合主键，外键';
COMMENT ON COLUMN report_audit_items.audit_id IS '审计编号，联合主键，外键';

/* =========================
   8. 常用索引
   ========================= */
CREATE INDEX idx_user_addresses_user ON user_addresses(user_id);
CREATE INDEX idx_tasks_publisher ON tasks(publisher_user_id);
CREATE INDEX idx_tasks_service ON tasks(service_type_id);
CREATE INDEX idx_tasks_node ON tasks(node_id);
CREATE INDEX idx_tasks_status ON tasks(task_status);
CREATE INDEX idx_tasks_created ON tasks(created_at);
CREATE INDEX idx_assign_task ON assign_records(task_id);
CREATE INDEX idx_assign_runner ON assign_records(runner_id);
CREATE INDEX idx_status_record ON task_status_logs(record_id);
CREATE INDEX idx_status_operator ON task_status_logs(operator_user_id);
CREATE INDEX idx_payments_record ON payments(record_id);
CREATE INDEX idx_payments_status ON payments(pay_status);
CREATE INDEX idx_refunds_payment ON refunds(payment_id);
CREATE INDEX idx_refunds_status ON refunds(process_status);
CREATE INDEX idx_complaints_record ON complaints(record_id);
CREATE INDEX idx_complaints_status ON complaints(process_status);
CREATE INDEX idx_settlements_runner ON settlements(runner_id);
CREATE INDEX idx_settlements_status ON settlements(settlement_status);
CREATE INDEX idx_audit_logs_object ON audit_logs(audit_object);
CREATE INDEX idx_reports_type_period ON reports(report_type, stat_period);

COMMIT;

PROMPT Oracle database schema created successfully.
