SET SERVEROUTPUT ON
SET FEEDBACK ON
SET PAGESIZE 200
SET LINESIZE 200

ALTER PLUGGABLE DATABASE ORCLPDB OPEN;
ALTER SESSION SET CONTAINER = ORCLPDB;

DECLARE
    user_count NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO user_count
    FROM dba_users
    WHERE username = 'APPUSER';

    IF user_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER APPUSER IDENTIFIED BY App123456';
        DBMS_OUTPUT.PUT_LINE('Created user APPUSER.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('User APPUSER already exists.');
        EXECUTE IMMEDIATE 'ALTER USER APPUSER IDENTIFIED BY App123456 ACCOUNT UNLOCK';
    END IF;
END;
/

GRANT CONNECT, RESOURCE TO APPUSER;
ALTER USER APPUSER QUOTA UNLIMITED ON USERS;

SELECT username, account_status FROM dba_users WHERE username = 'APPUSER';

EXIT
